### ISSUE TITLE
Heroku Ownership Required to automatically deploy

### ISSUE THREAD

**Issue by trystant** [substrakt/letsencrypt-heroku#14]
Hi,

I came upon this and was looking forward to installing this. I started the Heroku deploy wizard from the button on the README page, but when I specified the app (in this case "blackops-staging",  I got a response saying that the "application is not available". 
<img width="1440" alt="screenshot 2016-08-13 17 19 58" src="https://cloud.githubusercontent.com/assets/13509/17645682/aa853c34-617a-11e6-80ad-354aefce142c.png">

I'm assuming that this is because I am a collaborator on this app and not an owner. If this is correct, it might be good to specify that one needs to be an owner. 

According to the [Collaborator Permissions](https://devcenter.heroku.com/articles/collaborating#collaborator-permissions), the only items that a collaborator should not be able to do are:

* Add or remove paid add-ons
* Delete, transfer or rename the app
* View invoices

Considering that this is a free solution, I am not clear on whether doing this deploy requires ownership, or whether there are other reasons why the automatic deploy didn't work.

Thanks in advance.

**Comment by mlebkowski** [comment]
No, @trystant, this is a separate app that manages the certificate for your other applications. You shouldn’t use an existing apps name, but a new one, like `blackops-certificate-manager`

**Comment by maxehmookau** [comment]
Hi @trystant,

As @mlebkowski says, just to clarify, this project is a separate application that you can deploy to Heroku, it's not an add-on to add to existing Heroku apps.

I suggest naming it something like YOURNAME-certificate-management on heroku, or similar.

**Comment by trystant** [comment]
@mlebkowski and @maxehmookau 

Ah, eyes I got it. https://endbias-certificate-manager.herokuapp.com/ is live and working. Made things very easy. Thank you so much for this. I can close this ticket.
