### ISSUE TITLE
Stuck on Heroku certificate deployment

### ISSUE THREAD

**Issue by backspace** [substrakt/letsencrypt-heroku#16]
Hey, thanks for your work on this. I’m happy that the moment of free and easy SSL is approaching.

It seems like my installation isn’t working properly, as it never progresses beyond the `Deploying certificate to Heroku` stage. I’ve looked at the data in Redis but don’t see anything helpful there. I can see that CloudFlare has some ACME-related `TXT` records, which seems like a good sign.

When I run `heroku _certs:info` it says there are no certificates, which I think wouldn’t be the case if the process succeeded?

Let me know if I can provide any debugging information.

Also, I have a side question about something in the documentation:

> It doesn't currently add the CNAME records to CloudFlare once the SSL certificate has been generated.

Would the `CNAME` just be an alias for `applicationname.herokuapp.com`?

**Comment by maxehmookau** [comment]
Ok, so your second query first (it's easier), that's correct. Although it won't be in that form as the SNI plugin on Heroku overrides the DNS entries. Just keep an eye on it.

As for that first issue, that's puzzling. Chances are it's failing somewhere in the process and then not attaching the cert. By the looks of it, it's added the TXT record so the verification has worked as the cert has been generated. Are you 100% sure your Heroku API key is correct? That seems like the most likely cause of failure currently.

**Comment by backspace** [comment]
hmm, well just in case, I revoked the token and created a new one. On my first attempt, I got this error:

> Error creating new cert :: Authorizations for these names not found or expired: chromatin.ca

I tried again, and the same thing happened where it never progressed beyond `in_progress` an “Deploying certificate to Heroku”

**Comment by polkovnikov-ph** [comment]
Same issue. Just hangs on "Deploying certificate to Heroku".

**Comment by samknight** [comment]
I'm having the same issue here and currently looking for the cause.

**Comment by samknight** [comment]
Try creating a new oauth user to the account and adding the token to the ENV config. This worked for me but may not have been the same issue.
