### ISSUE TITLE
Get error message 'Not authenticated' when trying to hit generate certification endpoint

### ISSUE THREAD

**Issue by JaredPon** [substrakt/letsencrypt-heroku#17]
I'm having an issue where I am getting a response with message `Not authenticated` when trying to view the status_path.

It looks like I am getting a 403 because my AUTH_TOKEN is incorrect but i've pulled it straight form the heroku configs and have double checked that it's matching.

I get to the status page that shows status_path without any issues but when I check on the status I get `Not authenticated`

This is the request i'm submitting.

`https://herokuappname.herokuapp.com/certificate_generation/new/aaaa.com?subdomains=www,api&debug=0&app_name=aaaa-backend-loadbalancer&auth_token=XXXXXXX`

**Comment by maxehmookau** [comment]
Hi @JaredPon,

Is this closed because you solved the issue?
