### ISSUE TITLE
[question] Always null state

### ISSUE THREAD

**Issue by polkovnikov-ph** [substrakt/letsencrypt-heroku#19]
Here's a JSON from the state endpoint:

```javascript
{
  "token": "e...a",
  "status": null,
  "error": null,
  "domain": null,
  "subdomains": [],
  "message": null
}
```

What does that mean?

**Comment by samknight** [comment]
This potentially might be if you have too many TXT files on your cloudflare domain. Try removing any letsencrypt  TXT files from cloudflare and try again.

**Comment by polkovnikov-ph** [comment]
As it turned out, it's a result of not passing a `subdomains` parameter.
I don't know where did you get that info on TXT nodes, but if in such cases this library prints such messages, it's a topic for a bug report.

**Comment by maxehmookau** [comment]
Resolving in #20
