### ISSUE TITLE
Does not work with Free Dynos on Heroku

### ISSUE THREAD

**Issue by OrkoHunter** [substrakt/letsencrypt-heroku#38]
Hello,

As the README states, "Heroku has started giving out free SSL options", I'm not sure if that's correct.

```
2017-01-01T12:46:14.004441+00:00 app[worker.1]: ---> Provisioning Heroku application with new certificate
2017-01-01T12:46:14.099025+00:00 app[worker.1]: ---> Uploading new certificate
2017-01-01T12:46:14.205924+00:00 app[worker.1]: ----> Error: {"id":"invalid_params","message":"You need to be running on either Hobby or Professional dynos to be able to use SNI SSL."}
```

Here is the log from my `letsencrypt-heroku` when I tried to run it for my app.

**Comment by maxehmookau** [comment]
Ah, I see. Perhaps an issue of proper wording.

The SSL certificate and the endpoint itself are _technically_ free. But Heroku does have a restriction that the app must use Hobby dynos ($7/dyno/mo) or professional dynos ($25-500/dyno/mo)

There's nothing that can be done about this. It's simply a restriction of the Heroku platform. That said, you'd be more than welcome to submit a PR to make this restriction clearer in the README.

**Comment by niksumeiko** [comment]
I'm using Heroku free dyno for our staging/testing app, before it's promoted to production running on professional dyno. Therefore, it feels like it would be helpful to have simulate absolutely equal environment for staging app. Disappointed, Heroku add this limitation.

**Comment by maxehmookau** [comment]
I'm not Heroku. This is a 3rd party tool which is no longer supported. Your beef is with Heroku.

**Comment by prameshbajra** [comment]
Ahh!! After tiresome 2 hours of trying to add SSL Certifs to Free Dynos I came to this page. How sad 🤕  .
God Bless Devs 😋  
and thank you @maxehmookau  for clearing things out. Really helped.

**Comment by shivakumars** [comment]
> Ahh!! After tiresome 2 hours of trying to add SSL Certifs to Free Dynos I came to this page. How sad 🤕 .
> God Bless Devs 😋
> and thank you @maxehmookau for clearing things out. Really helped.

Me too :man_facepalming:

**Comment by prameshbajra** [comment]
> > Ahh!! After tiresome 2 hours of trying to add SSL Certifs to Free Dynos I came to this page. How sad face_with_head_bandage .
> > God Bless Devs yum
> > and thank you @maxehmookau for clearing things out. Really helped.
> 
> Me too

#SEDLIFE

**Comment by rajmondx** [comment]
This is probably why heroku doesnt support HTTP/2 (most implementations of HTTP/2 are end-to-end so they require you to provide a ssl at the beginning which doesnt allow Heroku to manage the SSLs anymore but on the other hand it provides more security for our apps).
