### ISSUE TITLE
"Invalid zone"

### ISSUE THREAD

**Issue by maxko87** [substrakt/letsencrypt-heroku#39]
I'm getting this error message from the API call:

```
{
"status": "error",
"message": "Invalid zone."
}
```

I'm copying the Zone ID directly from the "domain summary" section on Cloudflare. The Cloudflare API also returns the same Zone ID. 

Is there something else that would be causing this error?

**Comment by maxehmookau** [comment]
Zone is referring to the name of the zone, not the ID. Usually this is just the domain name. `substrakt.com` for example.

**Comment by maxko87** [comment]
Thanks, that worked!

**Comment by maxehmookau** [comment]
![Party Hard](http://33.media.tumblr.com/a47c786268bfa1e4970c9577da0a79da/tumblr_ndi5sguziN1rnjev4o1_500.gif)
